package Ventanas;

public class Interfaz extends javax.swing.JFrame {
//Creacion del metodo limpiar (funcion al boton limpiar campos)
    public void LimpiarCampos(){
        txtPeso.setText("");
        txtEstatura.setText("");
        txtResultadoIMC.setText("");
        txtResultadoEvaluacion.setText("");
        
    }
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
    //Linea para colocar la ventana enmedio de la pantalla
        initComponents();
        setLocationRelativeTo(null);
        //para no modificar el tañano de la ventana
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabelPeso = new javax.swing.JLabel();
        jLabelEstatura = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtOPcionF = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        txtResultadoIMC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResultadoEvaluacion = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Andalus", 1, 13)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jLabelPeso.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeso.setText("Peso:");
        getContentPane().add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabelEstatura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelEstatura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstatura.setText("Estatura:");
        getContentPane().add(jLabelEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, -1));
        getContentPane().add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculo de Indice de Masa Corporal ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 400, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("IMC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Calcula-tu-Peso-Ideal-y-IMC1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 140));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kg");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("m");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Calcular IMC ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 120, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("=");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtOPcionF.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtOPcionF.setForeground(new java.awt.Color(255, 255, 255));
        txtOPcionF.setText("F");
        getContentPane().add(txtOPcionF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 40, -1));

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("M");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        getContentPane().add(txtResultadoIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 120, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Resultado Evaluación:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        getContentPane().add(txtResultadoEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 310, 70));

        jLabelFondo.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //funcion del boton (salir)
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//Funcion del Boton limpiar 
        LimpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed
Double estatura,peso,total,imc;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Estableciendo los atributos para la operacion en el boton Calcular
        estatura=Double.parseDouble(txtEstatura.getText());
        peso=Double.parseDouble(txtPeso.getText());
        calcularIMC(estatura,peso);
        verificarSituacion();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
private void verificarSituacion(){
    if(imc <=18.5){
        txtResultadoEvaluacion.setText("su peso esta por deja de lo ideal");
    }
    else if(imc >=18.5 && imc <=24.9 ){
 txtResultadoEvaluacion.setText("Se encuentra en un peso normal");   
}
    if(imc >25 && imc <= 29.9){
    txtResultadoEvaluacion.setText("Estas en Sobrepeso");   
}
else if(imc >30 && imc <= 34.9){
  txtResultadoEvaluacion.setText("Estas en la etapa I de Obesidad");  
}
if(imc >35 && imc<=39.9){
   txtResultadoEvaluacion.setText("Estas en la etapa II de Obesidad");   
}
else if(imc >40 && imc <= 49.9 ){
    txtResultadoEvaluacion.setText("Estas en la etapa III de Obesidad");   
}
if(imc >=50){
    txtResultadoEvaluacion.setText("Estas en la etapa IV de Obesidad");   
}
}
    
    private void calcularIMC(double estatura,double peso){
    imc=peso/(estatura*estatura);
    txtResultadoIMC.setText(String.valueOf(imc));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEstatura;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPeso;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JCheckBox txtOPcionF;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtResultadoEvaluacion;
    private javax.swing.JTextField txtResultadoIMC;
    // End of variables declaration//GEN-END:variables
}
